version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  auth:
    container_name: auth-app
    image: auth-app
    build:
      context: auth-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db   

  fetch:
      container_name: fetch-app
      image: fetch-app
      build:
        context: fetch-app
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
  
volumes:
  db:
   driver: local
